### ISSUE TITLE
IVSD and IVC for NLAY=1

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/mfusg#29]
I thought that in mfusg if we had a model with cells that were overlying and underlying one another, that we could put all the cells into one layer, and just set IVC appropriately.  I think I had done that in the past.  But a colleague in the Netherlands, just pointed out that IVC is only read if IVSD = 1 AND NLAY > 1.  Code is below.  Is this a new requirement?  Is there any reason we don't read IVC in this case?  The NLAY > 1 requirement does not seem to be documented in the instructions.

```
C10-----FILL VERTICAL CONNECTION ARRAY IVC.
      IF(IVSD.LE.0)THEN
C10A------compute IVC for IVSD. LE. 0
        DO K=1,NLAY
          NNDLAY = NODLAY(K)
          NSTRT = NODLAY(K-1)+1
          DO N=NSTRT,NNDLAY
C10A1-----LOOP OVER CONNECTIONS OF NODE N AND FILL
          DO II = IA(N)+1,IA(N+1)-1
            JJ = JA(II)
            IIS = JAS(II)
            IF(JJ.LE.N.OR.JJ.GT.NODES) CYCLE
            IF(JJ.GT.NNDLAY)THEN
              IVC(IIS) = 1  ! LAYER IS BELOW
            ELSE
              IVC(IIS) = 0
            ENDIF
          ENDDO
          ENDDO
        ENDDO
      ELSE
C10B----read IVC, for IVSD. GT. 0.
        IF(NLAY.GT.1) 
     *  CALL U1DINTNJA(IVC,IATMP,ANAME,NJATMP,INDIS,IOUT,IDSYMRD)
      ENDIF
```

**Comment by sorab** [comment]
The LAYCON(K+1) issue is also readily solved (done) but not sure how this will affect LAKE package where NALY.eq.1 is also considered in several places.

**Comment by sorab** [comment]
We could document that LAKE package may want the layers separated and close the issue.
