### ISSUE TITLE
Bug in EVT Package

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/mfusg#35]
Marius,
 
The variable “NODES” is not being passed into EVT8U1RP. Please see below – you need to add the highlighted part to the subroutine (NODES). If you want an executable I can provide you with one with this fixed.
 
Sorab
 
```
     SUBROUTINE GWF2EVT8U1RP(IN)
C     ******************************************************************
C     READ EVAPOTRANSPIRATION DATA
C     ******************************************************************
C
C        SPECIFICATIONS:
C     ------------------------------------------------------------------
      USE GLOBAL,      ONLY:IOUT,NCOL,NROW,NLAY,DELR,DELC,IFREFM,NODLAY,
     1  AREA,IUNSTR,NODES
```

**Comment by christianlangevin** [comment]
Fixed with https://github.com/MODFLOW-USGS/mfusg/commit/585e69068a155e063df4072e6e5ec2f5588b708e
